version: '3.7'
services:
  twigram:
    image: twigram:latest

    environment:
      - DEBUG=false
      - TOKEN=""
      - INTERVAL=30           # interval for polling mode
      - WEB_URL=""            # you web url for webhook mode, e.g. https://twigram.example.com
      - PORT=58081            # port for local listening, you need a reverse proxy to forward traffic to this port
      - TWITTER_USERNAME=""
      - TWITTER_EMAIL=""
      - TWITTER_PASSWORD=""
      - TWITTER_COOKIE=""

    healthcheck:
      test: "curl --silent --fail http://127.0.0.1:58081/health || exit 1"
      interval: 1m0s
      timeout: 15s
      retries: 0
      start_period: 0s
